### ISSUE TITLE
我用GNU/Linux，OrangePi_Lite2_Ubuntu16.04_Desktop_Xfce_Beta.tar.gz不能下载

### ISSUE THREAD

**Issue by zaoqi** [orangepi-xunlong/OrangePiH6_kernel#1]
+ 百度云盘 必须安装Windows客户端
+ MEGA云盘在境内不能正常使用
+ 我的手机没装Android，也是GNU/Linux
+ 论坛没有完全成功注册
+ https://github.com/orangepi-xunlong/OrangePi_Build 需要root，我不想用

**Comment by zaoqi** [comment]
@orangepi-xunlong @leeboby @0pcom @Matze-M @cbbc @BuddyZhang1

**Comment by zaoqi** [comment]
@OrangePi

**Comment by Matze-M** [comment]
Can you please comment in English?

**Comment by zaoqi** [comment]
@Matze-M
I'm using GNU/Linux
I can't download `OrangePi_Lite2_Ubuntu16.04_Desktop_Xfce_Beta.tar.gz`
+ 百度云盘 requires Windows client.
+ MEGA cannot be used in China.
+ https://github.com/orangepi-xunlong/OrangePi_Build requires root,I don't want
+ I didn‘t successfully fully register in the forum.

**Comment by Matze-M** [comment]
Did you tried Wget or git to download ?

**Comment by zaoqi** [comment]
@Matze-M where?

**Comment by zaoqi** [comment]
@Matze-M 百度云盘 did not support wget now

**Comment by Matze-M** [comment]
U mean the official image from xulong ?

**Comment by Matze-M** [comment]
@zaoqi 百度云盘 ?

**Comment by zaoqi** [comment]
@Matze-M  is the official image from xulong
百度云盘 requires Windows client
百度云盘 did not support HTTP or provide GNU/Linux client

**Comment by Matze-M** [comment]
Aha this means baidu 😂

**Comment by Matze-M** [comment]
Should i download the image and send you a link ? Is web.de blocked in China ?

**Comment by zaoqi** [comment]
@Matze-M It is not blocked

**Comment by Matze-M** [comment]
Ah OK i will download and send it to u if u want pls send me a private message

**Comment by zaoqi** [comment]
@Matze-M What is 'pls'?

**Comment by Matze-M** [comment]
Please

**Comment by zaoqi** [comment]
@Matze-M What's 'send me a private message'?

**Comment by zaoqi** [comment]
@Matze-M ?

**Comment by Matze-M** [comment]
Write me a E-Mail

**Comment by zaoqi** [comment]
@Matze-M zaomir@outlook.com

**Comment by orangepi-xunlong** [comment]
@Matze-M Thanks for the help!
