### ISSUE TITLE
Nothing is shown while booting OrangePi_Lite2_Ubuntu16.04_Server_BETA.img

### ISSUE THREAD

**Issue by csukuangfj** [orangepi-xunlong/OrangePiH6_kernel#2]
After downloading `OrangePi_Lite2_Ubuntu16.04_Server_BETA.img` and flashing it to the
tf card, the screen shows nothing when orange pi lite 2 is started.

Note that HDMI is used to connect to the display.

Is there anything that should be done to get something displayed on the screen ?

**Comment by orangepi-xunlong** [comment]
The code and image have been updated, please try the latest, thank you!

**Comment by csukuangfj** [comment]
The reply comes tooooo late. Thank you anyway.
